name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
    - run: pnpm install
    - run: pnpm run build
    - run: pnpm run publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update build artifacts and release
